sudo: required
services:
  - docker

before_install:
  - docker build -t mchoi3000/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true mchoi3000/react-test npm test

after_success:
  - docker build -t mchoi3000/multi-client ./client
  - docker build -t mchoi3000/multi-nginx ./nginx
  - docker build -t mchoi3000/multi-server ./server
  - docker build -t mchoi3000/multi-worker ./worker
  # Log in to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push mchoi3000/multi-client
  - docker push mchoi3000/multi-nginx
  - docker push mchoi3000/multi-server
  - docker push mchoi3000/multi-worker

# deploy: 
#   provider: elasticbeanstalk
#   region: us-west-2
#   app: multi-docker
#   env: MultiDocker-env
#   bucket_name: elasticbeanstalk-us-west-2-206645836867
#   bucket_path: docker-multi
#   on:
#     branch: master
#   access_key_id: 
#     secure: $AWS_ACCESS_KEY
#   secret_access_key:
#     secure: $AWS_SECRET_KEY
